# SPDX-License-Identifier: Apache-2.0
"""A rolling-origin backtest is only worth running if no fold leaks.

The layout bug this guards against is easy to make and invisible in the output:
a test fold that also trained the model produces beautiful numbers that mean
nothing. So these tests check the splits, not the metrics.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

_SPEC = importlib.util.spec_from_file_location(
    "sentinel_backtest",
    Path(__file__).resolve().parents[1] / "scripts" / "run_backtest.py",
)
assert _SPEC and _SPEC.loader
backtest = importlib.util.module_from_spec(_SPEC)
# The dataclass decorator resolves its own module, so it must be importable.
sys.modules[_SPEC.name] = backtest
_SPEC.loader.exec_module(backtest)


def _rows(**kwargs):
    """Run the backtest and hand back the origin rows plus the scenario order."""
    scenarios = [f"bo{i:02d}" for i in range(14)]
    params = {"scenarios": scenarios, "origins": 3, "fold_size": 2}
    params.update(kwargs)
    rows, _warnings = backtest.run_backtest(**params)
    return rows, scenarios


def test_no_fold_ever_trains_itself() -> None:
    rows, _ = _rows()
    assert len(rows) == 3
    for row in rows:
        assert set(row.train_scenarios).isdisjoint(row.test_scenarios)
        assert set(row.validation_scenarios).isdisjoint(row.test_scenarios)
        assert set(row.train_scenarios).isdisjoint(row.validation_scenarios)


def test_test_folds_advance_through_the_data() -> None:
    rows, scenarios = _rows()
    seen_tests: list[str] = []
    for index, row in enumerate(rows):
        assert row.test_scenarios == tuple(scenarios[(index + 2) * 2 : (index + 3) * 2])
        seen_tests.extend(row.test_scenarios)
    # Each fold is scored exactly once: no fold is silently dropped or re-scored.
    assert len(seen_tests) == len(set(seen_tests))


def test_earliest_origin_still_has_training_data() -> None:
    rows, _ = _rows()
    assert rows[0].train_scenarios
    for row in rows:
        assert row.train_scenarios


def test_training_window_grows_with_each_origin() -> None:
    rows, _ = _rows()
    for earlier, later in zip(rows, rows[1:], strict=False):
        assert len(later.train_scenarios) > len(earlier.train_scenarios)


def test_too_few_scenarios_is_an_explicit_error() -> None:
    with pytest.raises(ValueError, match="need"):
        backtest.run_backtest(scenarios=[f"x{i}" for i in range(5)], origins=3, fold_size=2)


def test_every_origin_reports_a_measured_threshold_and_psi() -> None:
    rows, _ = _rows()
    for row in rows:
        assert 0.0 < row.threshold < 1.0
        assert row.max_feature_psi >= 0.0
        assert row.worst_feature != ""
        assert 0.0 <= row.direction_accuracy <= 1.0
        assert row.test_scenarios


def test_synthetic_data_is_disclaimed_in_every_rendered_report() -> None:
    rows, _ = _rows(horizon=2)
    payload = {
        "backtest_version": backtest.BACKTEST_VERSION,
        "dataset_id": "synthetic",
        "generated_at": "2026-01-01T00:00:00+00:00",
        "origins": 3,
        "fold_size": 2,
        "horizon": 2,
        "rows": [row.__dict__ for row in rows],
        "summary": backtest._summarise(rows),
        "warnings": [
            "All figures are from synthetic data generated by this run. They do "
            "not describe real network traffic."
        ],
    }
    rendered = backtest._render(payload)
    assert "synthetic" in rendered
    assert "do not describe real network traffic" in rendered
