#!/usr/bin/env python3
"""Auto-generate docs/FEATURE_CATALOG.md from AGGREGATION_POLICY."""

from __future__ import annotations

import pathlib

from trajectory.state_builder import (
    _UNDEFINED_FOR_SINGLE,
    AGGREGATION_POLICY,
    FEATURE_VERSION,
    LEGACY_ALIASES,
)

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "FEATURE_CATALOG.md"

# ── Descriptions per base feature ──────────────────────────────────────────
DESCRIPTIONS: dict[str, str] = {
    "bytes": "Total bytes transferred in the window.",
    "packets": "Total packets transferred in the window.",
    "duration": "Flow duration within the window.",
    "payload_size": "Application-layer payload size.",
    "ttl": "IP time-to-live value.",
    "tcp_window_size": "TCP receive window size.",
    "iat_mean": "Mean inter-arrival time between events in the same flow.",
    "iat_variance": "Variance of inter-arrival times.",
    "iat_max": "Maximum inter-arrival time.",
    "bidirectional_ratio": "Bytes from source / (bytes from source + bytes to source).",
    "syn_count": "TCP SYN flag count (bitmask decomposed).",
    "ack_count": "TCP ACK flag count (bitmask decomposed).",
    "fin_count": "TCP FIN flag count (bitmask decomposed).",
    "rst_count": "TCP RST flag count (bitmask decomposed).",
    "urg_count": "TCP URG flag count (bitmask decomposed).",
    "failed_auth": "Count of failed authentication attempts.",
    "auth_attempt": "Count of authentication attempts (success + failure).",
    "source_port": "Source TCP/UDP port number.",
    "destination_port": "Destination TCP/UDP port number.",
    "protocol": "IP protocol number.",
    "tcp_flags": "Raw TCP flags bitmask (unique values only).",
}

# Count features that appear as legacy flat names (computed in _build_state)
COMPUTED_FEATURES: dict[str, str] = {
    "event_count": "Number of events in the window.",
    "flow_event_count": "Number of flow-type events.",
    "packet_event_count": "Number of packet-type events.",
    "external_destination_count": "Flows to external / 1.2.3.4 destinations.",
    "high_port_ratio": "Fraction of flows with source_port > 1024.",
}


def _agg_note(agg: str) -> str:
    if agg in _UNDEFINED_FOR_SINGLE:
        return f"{agg} (absent when window has < 2 events)"
    return agg


def main() -> None:
    lines: list[str] = []
    lines.append(f"# Feature Catalog — {FEATURE_VERSION}\n")
    lines.append(
        "> Auto-generated by `scripts/generate_feature_catalog.py`. Do not edit by hand.\n"
    )

    # ── Computed features ────────────────────────────────────────────────
    lines.append("## Computed Features\n")
    lines.append("| Feature | Description |")
    lines.append("|---------|-------------|")
    for name, desc in sorted(COMPUTED_FEATURES.items()):
        lines.append(f"| `{name}` | {desc} |")
    lines.append("")

    # ── Aggregated features ──────────────────────────────────────────────
    lines.append("## Aggregated Features\n")
    lines.append("| Base Feature | Enriched Name | Aggregation | Description |")
    lines.append("|-------------|---------------|-------------|-------------|")
    for base, aggs in sorted(AGGREGATION_POLICY.items()):
        desc = DESCRIPTIONS.get(base, "")
        for agg in aggs:
            out_name = f"{base}_{agg}"
            lines.append(f"| `{base}` | `{out_name}` | {_agg_note(agg)} | {desc} |")
    lines.append("")

    # ── Legacy aliases ───────────────────────────────────────────────────
    lines.append("## Legacy Aliases\n")
    lines.append(
        "Old flat feature names retained for backward compatibility. "
        "Deprecated — use enriched names instead.\n"
    )
    lines.append("| Legacy Name | Enriched Name |")
    lines.append("|-------------|---------------|")
    for legacy, enriched in sorted(LEGACY_ALIASES.items()):
        lines.append(f"| `{legacy}` | `{enriched}` |")
    lines.append("")

    # ── Schema width ─────────────────────────────────────────────────────
    total_enriched = sum(len(aggs) for aggs in AGGREGATION_POLICY.values())
    total_computed = len(COMPUTED_FEATURES)
    lines.append("## Statistics\n")
    lines.append(f"- **Version**: `{FEATURE_VERSION}`")
    lines.append(f"- **Base features in policy**: {len(AGGREGATION_POLICY)}")
    lines.append(f"- **Enriched feature slots**: {total_enriched}")
    lines.append(f"- **Computed features**: {total_computed}")
    lines.append(f"- **Total possible features**: {total_enriched + total_computed}")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
