"""What does a stealthier attacker do to the model, and how long until we notice?

    uv run python scripts/run_drift_report.py

Trains on one attack style, then meets another: the same generator with a
shorter lateral phase, which is a real property of the generator rather than
noise added to a feature vector. Measures what the shift does to Brier, to
calibration, and to the conformal interval's coverage promise, then streams
post-shift blocks through an unsupervised monitor built on the *shipped* PSI and
reports the detection delay in windows.

The monitor's trip point is calibrated against its own pre-shift null, because
`sentinel.drift` bands PSI at hardcoded 0.10 and 0.25 and nothing in the codebase
can say what false-alarm rate those correspond to. This run says so out loud.

Synthetic data, generated by this run. A shift measured on a generator is a
statement about the generator.
"""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
from sklearn.linear_model import LogisticRegression

from sentinel.conformal import SplitConformal
from sentinel.drift_monitor import (
    DEFAULT_WINDOW,
    DRIFT_MONITOR_VERSION,
    WINDOW_SWEEP,
    DriftMonitor,
    ShiftOutcome,
    describe,
    detection_delay,
    false_alarm_rate_at,
    sweep_aggregation,
)
from sentinel.features import fit_feature_schema, vectorize_states
from sentinel.synthetic import DATASET_ID, generate_labelled_states
from sentinel.targets import build_sequence_samples, make_split_manifest

BEFORE = [f"dra{i:02d}" for i in range(10)]
AFTER = [f"drb{i:02d}" for i in range(10)]
# The shift: same generator, attacker nearly three times quicker through the
# lateral phase, so each window carries far less of the transfer.
BEFORE_LATERAL_MINUTES = 8
AFTER_LATERAL_MINUTES = 3
LEVEL = 0.99


def _cohort(scenarios, seed, lateral_minutes):
    labelled = generate_labelled_states(
        scenarios,
        seed=seed,
        window_seconds=60,
        stride_seconds=60,
        lateral_minutes=lateral_minutes,
    )
    samples = build_sequence_samples(labelled, sequence_length=2, horizon=1)
    return labelled, samples, {item.state_key: item for item in labelled}


def _matrix(samples, states_by_key, schema):
    rows = [states_by_key[s.input_state_keys[-1]].state for s in samples]
    matrix = vectorize_states(rows, schema)
    labels = np.array([1.0 if s.target.target_infiltration else 0.0 for s in samples])
    return matrix, labels, np.array([s.scenario_id for s in samples])


def _baseline_windows(schema, seed):
    """A separate cohort at the pre-shift settings, disjoint from everything else.

    This is the period the monitor watches *before* the attacker changes, and it
    is what makes the false-alarm count a rate rather than an artefact of where
    the stream happened to start. It is generated at a different seed so it shares
    no windows with the reference or the null.
    """
    labelled = generate_labelled_states(
        [f"drbase{i:02d}" for i in range(4)],
        seed=seed,
        window_seconds=60,
        stride_seconds=60,
        lateral_minutes=BEFORE_LATERAL_MINUTES,
    )
    samples = build_sequence_samples(labelled, sequence_length=2, horizon=1)
    return _matrix(samples, {i.state_key: i for i in labelled}, schema)[0]


def _coverage(conformal, predictions, truth) -> float:
    """Fraction of windows whose interval contains the true label."""
    covered = [
        conformal.predict(float(p)).covers(float(t))
        for p, t in zip(predictions, truth, strict=True)
    ]
    return float(np.mean(covered))


def run(seed: int = 61, coverage: float = 0.9) -> tuple[dict, ShiftOutcome]:
    before_labelled, before_samples, before_by_key = _cohort(BEFORE, seed, BEFORE_LATERAL_MINUTES)
    after_labelled, after_samples, after_by_key = _cohort(AFTER, seed + 1, AFTER_LATERAL_MINUTES)
    manifest = make_split_manifest(BEFORE, seed=seed)

    # Fit the schema and the model on the pre-shift world only. The shifted
    # cohort is never seen during fitting, schema selection or calibration.
    schema = fit_feature_schema([item.state for item in before_labelled])
    x_before, y_before, scenario_before = _matrix(before_samples, before_by_key, schema)
    x_after, y_after, _ = _matrix(after_samples, after_by_key, schema)

    train_rows = np.array(
        [i for i, s in enumerate(scenario_before) if s in manifest.train_scenarios]
    )
    validation_rows = np.array(
        [i for i, s in enumerate(scenario_before) if s in manifest.validation_scenarios]
    )
    model = LogisticRegression(max_iter=2000, random_state=seed)
    model.fit(x_before[train_rows], y_before[train_rows])

    def brier(rows_x, rows_y, which) -> float:
        predicted = model.predict_proba(rows_x[which])[:, 1]
        return float(np.mean((predicted - rows_y[which]) ** 2))

    in_distribution = {
        "brier": brier(x_before, y_before, validation_rows),
        "attack_rate": float(y_before[validation_rows].mean()),
    }
    shifted = {
        "brier": brier(x_after, y_after, np.arange(y_after.size)),
        "attack_rate": float(y_after.mean()),
    }

    # Conformal coverage on both sides, fitted on the pre-shift validation split.
    validation_predictions = model.predict_proba(x_before[validation_rows])[:, 1]
    conformal = SplitConformal(coverage=coverage).fit(
        validation_predictions, y_before[validation_rows]
    )
    covered_before = _coverage(conformal, validation_predictions, y_before[validation_rows])
    covered_after = _coverage(conformal, model.predict_proba(x_after)[:, 1], y_after)

    # The monitor: reference from the before-cohort's validation scenarios, the
    # trip point from its training scenarios, the control from a third cohort.
    reference = x_before[validation_rows]
    null_rows = x_before[train_rows]
    baseline_rows = _baseline_windows(schema, seed + 2)
    stream = np.vstack([baseline_rows, x_after])
    onset = int(baseline_rows.shape[0])

    sweep = sweep_aggregation(
        reference, list(schema.names), null_rows, stream, onset, WINDOW_SWEEP, level=LEVEL
    )
    monitor = DriftMonitor().calibrate(
        reference, list(schema.names), null_rows, level=LEVEL, window=DEFAULT_WINDOW
    )
    verdicts = monitor.stream(stream)
    delay = detection_delay(verdicts, onset)
    reported = next(row for row in sweep if row["rolling_window"] == DEFAULT_WINDOW)

    # The bands that `sentinel.drift` used to hardcode, kept as literals so this
    # report can still price them. They are not exported any more - the point of
    # the change was that they meant nothing - but their measured false-alarm rate
    # is the argument for the change, so the report has to be able to produce it.
    legacy_stable, legacy_moderate = 0.10, 0.25
    shipped_bands = {
        str(threshold): rate
        for threshold, rate in false_alarm_rate_at(
            reference, list(schema.names), baseline_rows, (legacy_stable, legacy_moderate)
        ).items()
    }
    outcome = ShiftOutcome(
        shift_name=(
            f"lateral phase shortened from {BEFORE_LATERAL_MINUTES} to "
            f"{AFTER_LATERAL_MINUTES} minutes"
        ),
        in_distribution=in_distribution,
        shifted=shifted,
        coverage_in_distribution=covered_before,
        coverage_shifted=covered_after,
        nominal_coverage=coverage,
        delay=delay,
        false_alarms=reported["false_alarms_pre_shift"],
        control_windows=reported["pre_shift_windows"],
        note=(
            "Coverage is marginal over the shifted windows, not conditional on a "
            "window being an attack, and the two cohorts differ in attack rate as "
            "well as in style, so the coverage gap mixes the two effects."
        ),
    )
    payload = {
        "version": DRIFT_MONITOR_VERSION,
        "dataset_id": DATASET_ID,
        "generated_at": datetime.now(UTC).isoformat(),
        "train_windows": int(train_rows.size),
        "validation_windows": int(validation_rows.size),
        "baseline_windows": int(baseline_rows.shape[0]),
        "shifted_windows": int(y_after.size),
        "shift_onset_block": onset,
        "outcome": outcome.as_dict(),
        "monitor": monitor.as_dict(),
        "sweep": sweep,
        "shipped_band_false_alarm_rates": shipped_bands,
        "exceeded_blocks": [v.as_dict() for v in verdicts if v.exceeded],
        "warnings": [
            "All figures are from synthetic data generated by this run; they "
            "describe the generator, not any real network.",
            "The model, the feature schema and the conformal interval are all "
            "fitted on pre-shift windows only. The shifted cohort is scored once, "
            "at the end.",
            f"The trip point is a quantile of this data's own pre-shift null "
            f"({monitor.n_null} windows), not a literature cutoff. sentinel.drift "
            "bands PSI at 0.10 and 0.25; this run does not confirm those levels "
            "are achievable here and reports the rate that is.",
            f"Verdicts aggregate {DEFAULT_WINDOW} windows, which is stated rather "
            "than chosen, so the delay cannot be smaller than "
            f"{DEFAULT_WINDOW - 1} blocks.",
        ],
    }
    return payload, outcome


def _render(payload: dict) -> str:
    outcome = payload["outcome"]
    interval = outcome["interval"]
    detection = outcome["detection"]
    lines = [
        "# Drift and detection delay",
        "",
        f"- version: `{payload['version']}`",
        f"- dataset: `{payload['dataset_id']}` (**synthetic**, generated by this run)",
        f"- generated: {payload['generated_at']}",
        f"- train windows **{payload['train_windows']}**, validation windows "
        f"**{payload['validation_windows']}**, control windows "
        f"**{payload['baseline_windows']}**, shifted windows "
        f"**{payload['shifted_windows']}**",
        "",
        f"**Shift applied:** {outcome['shift']}.",
        "",
        "## What the shift did to the model",
        "",
        "| | in distribution | after the shift |",
        "|---|---|---|",
        f"| Brier (lower better) | {outcome['in_distribution']['brier']:.4f} | "
        f"{outcome['shifted']['brier']:.4f} |",
        f"| attack rate | {outcome['in_distribution']['attack_rate']:.3f} | "
        f"{outcome['shifted']['attack_rate']:.3f} |",
        "",
        "## What the shift did to the interval's promise",
        "",
        f"- promised: **{interval['nominal']:.0%}**",
        f"- delivered before the shift: **{interval['in_distribution']:.1%}**",
        f"- delivered after the shift: **{interval['shifted']:.1%}**",
        "",
        outcome["note"],
        "",
        "## How long until the monitor noticed",
        "",
        f"- trip point: quantile {payload['monitor']['null_level']} of the pre-shift "
        f"null ({payload['monitor']['n_null_windows']} windows) = "
        f"PSI {payload['monitor']['threshold']:.3f}",
        f"- shift began at block {payload['shift_onset_block']} of the stream",
    ]
    if detection["detected"]:
        lines.append(
            f"- **tripped after {detection['delay_windows']} block(s)**, on "
            f"`{detection['feature']}`"
        )
    else:
        lines.append(f"- **never tripped** in {detection['n_windows']} blocks")
    lines += [
        f"- false alarms before the shift: {outcome['false_alarms']} of "
        f"{outcome['control_windows']} blocks",
        "",
        "## The block size decides whether the monitor works at all",
        "",
        "Reported whole rather than tuned to the value that looks best. A monitor "
        "worth having trips after the shift and stays quiet before it.",
        "",
        "| windows/block | false alarms pre-shift | detections post-shift | delay | trip point |",
        "|---|---|---|---|---|",
    ]
    for row in payload["sweep"]:
        lines.append(
            f"| {row['rolling_window']} | {row['false_alarms_pre_shift']}/"
            f"{row['pre_shift_windows']} | {row['detections_post_shift']}/"
            f"{row['post_shift_windows']} | {row['delay_windows']} | "
            f"{row['threshold']:.3f} |"
        )
    bands = payload["shipped_band_false_alarm_rates"]
    lines += [
        "",
        "## What the shipped 0.10 / 0.25 bands actually mean here",
        "",
        "Measured on the same held-out pre-shift blocks, so this is a direct answer "
        "to what `sentinel.drift.band_of` is worth at this block size.",
        "",
        "| band | worst feature | median single feature |",
        "|---|---|---|",
    ]
    for threshold in (0.10, 0.25):  # the legacy bands, now literals
        lines.append(
            f"| {threshold} | {bands[str(threshold)]:.0%} | "
            f"{bands[f'median_single_feature_at_{threshold}']:.0%} |"
        )
    lines += [
        "",
        "Both bands fire on essentially every held-out block, so `band_of` answers "
        "`significant` for almost any input a caller sends. That is a statement "
        "about the constants, not about the aggregation.",
    ]
    lines += [
        "",
        f"Reported above at {DEFAULT_WINDOW} windows per block, stated rather than "
        "chosen. **The false-alarm rate before the shift is as high as the detection "
        "rate after it at every setting tried**, so on this data the monitor cannot "
        "tell an attacker getting stealthier from one more cohort of the same "
        "generator. It is a tripwire to investigate, not an alarm to page on.",
        "",
        "## Warnings",
        "",
    ]
    lines += [f"- {w}" for w in payload["warnings"]]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=61)
    parser.add_argument("--coverage", type=float, default=0.9)
    parser.add_argument("--output", default="reports/generated/drift")
    args = parser.parse_args()

    payload, outcome = run(seed=args.seed, coverage=args.coverage)
    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    (out / "drift.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    (out / "drift.md").write_text(_render(payload), encoding="utf-8")

    print(describe(outcome))
    print()
    for row in payload["sweep"]:
        print(
            f"  block={row['rolling_window']:>4}  "
            f"false alarms {row['false_alarms_pre_shift']:>3}/{row['pre_shift_windows']:<4}  "
            f"detections {row['detections_post_shift']:>3}/{row['post_shift_windows']:<4}  "
            f"delay={row['delay_windows']}"
        )
    for warning in payload["warnings"]:
        print(f"warning: {warning}")
    print(f"drift_json={out / 'drift.json'}")
    print(f"drift_md={out / 'drift.md'}")


if __name__ == "__main__":
    main()
