"""Calibration report: reliability, ECE and Brier decomposition, per model.

    uv run python scripts/run_calibration_report.py

Every number this project publishes about the quality of its own probabilities
should be reproducible by a command. This one covers two models that were being
described only by a threshold metric:

- the **baseline**, which this run found to be well calibrated (test ECE 0.054),
  so the report says so rather than manufacturing a problem;
- the **world model's risk head**, which was badly scaled in the mid-range.

It also applies the isotonic recalibration where one is fitted and prints the
held-out before/after, so the correction is a measurement rather than a claim.

Both models are measured on **synthetic** data generated by this run. The report
is not a field benchmark and says so in its own output.
"""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path

import numpy as np

from sentinel.baseline import train_baseline
from sentinel.config import BaselineConfig
from sentinel.conformal import (
    brier_decomposition,
    expected_calibration_error,
    reliability_table,
)
from sentinel.features import fit_feature_schema, vectorize_states
from sentinel.isotonic import IsotonicCalibrator
from sentinel.metrics import compute_binary_metrics
from sentinel.synthetic import DATASET_ID, generate_labelled_states
from sentinel.targets import build_sequence_samples, make_split_manifest
from sentinel.world_model.train import WorldModelConfig, build_world_sequences, train_world_model

REPORT_VERSION = "calibration-report-v1"
SCENARIOS = [f"cal{i:02d}" for i in range(10)]


def _summarise(name: str, scores: np.ndarray, labels: np.ndarray) -> dict:
    parts = brier_decomposition(scores, labels)
    return {
        "split": name,
        "n": int(labels.size),
        "positives": int(labels.sum()),
        "base_rate": parts["base_rate"],
        "mean_predicted": float(scores.mean()),
        "bias": float(scores.mean() - labels.mean()),
        "ece": expected_calibration_error(scores, labels),
        "brier": parts["brier"],
        "reliability": parts["reliability"],
        "resolution": parts["resolution"],
        "uncertainty": parts["uncertainty"],
        "skill_vs_base_rate": parts["skill_vs_base_rate"],
        "reliability_table": reliability_table(scores, labels, bins=10),
    }


def _threshold_sweep(labels: np.ndarray, scores: np.ndarray) -> list[dict]:
    """Why a single threshold metric hides a calibration problem.

    F1 peaks somewhere, but the precision/recall trade at that point is what
    matters operationally, and a badly-scaled head reaches a good F1 while
    lying about the middle of its range.
    """
    rows = []
    for threshold in (0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99):
        metrics = compute_binary_metrics(labels, scores, threshold=threshold)
        rows.append(
            {
                "threshold": threshold,
                "f1": metrics.f1,
                "precision": metrics.precision,
                "recall": metrics.recall,
                "false_positive_rate": metrics.false_positive_rate,
            }
        )
    return rows


def run_report(seed: int = 23) -> dict:
    labelled = generate_labelled_states(SCENARIOS, seed=seed, window_seconds=60, stride_seconds=60)
    manifest = make_split_manifest(SCENARIOS, seed=seed)
    train_ids = manifest.train_scenarios

    payload: dict = {
        "report_version": REPORT_VERSION,
        "dataset_id": DATASET_ID,
        "generated_at": datetime.now(UTC).isoformat(),
        "warnings": [
            "All figures are from synthetic data generated by this run. They "
            "describe the generator, not any real network.",
        ],
    }

    # ── baseline ───────────────────────────────────────────────────────
    schema = fit_feature_schema([i.state for i in labelled if i.scenario_id in train_ids])
    samples = build_sequence_samples(labelled, sequence_length=2, horizon=1)
    baseline = train_baseline(
        labelled,
        samples,
        manifest,
        config=BaselineConfig(decision_threshold=0.5),
        seed=seed,
    )
    states_by_key = {item.state_key: item for item in labelled}

    def baseline_scores(scenario_ids: list[str]) -> tuple[np.ndarray, np.ndarray]:
        selected = [s for s in samples if s.scenario_id in scenario_ids]
        if not selected:
            return np.array([]), np.array([])
        states = [states_by_key[s.input_state_keys[-1]].state for s in selected]
        matrix = vectorize_states(states, baseline.result.feature_schema)
        probabilities = np.asarray(baseline.model.predict_proba(matrix)[:, 1], dtype=float)
        labels = np.array([1.0 if s.target.target_infiltration else 0.0 for s in selected])
        return probabilities, labels

    payload["baseline"] = {
        "splits": [
            _summarise(name, *baseline_scores(ids))
            for name, ids in (
                ("train", train_ids),
                ("validation", manifest.validation_scenarios),
                ("test", manifest.test_scenarios),
            )
            if baseline_scores(ids)[0].size
        ],
        "threshold_sweep": _threshold_sweep(*baseline_scores(manifest.test_scenarios)),
        "conformal_coverage": baseline.result.conformal_coverage,
    }

    # ── world model ────────────────────────────────────────────────────
    world_config = WorldModelConfig(
        hidden_size=32,
        latent_dim=32,
        max_epochs=6,
        kl_anneal_epochs=2,
        imagination_samples=16,
        rollout_steps=3,
    )
    world = train_world_model(
        labelled,
        manifest,
        feature_schema=schema,
        config=world_config,
        seed=seed,
        sequence_length=4,
    )
    sequences = build_world_sequences(
        labelled, sequence_length=4, stage_vocabulary=world.result.stage_vocabulary
    )

    def world_scores(scenario_ids: list[str]) -> tuple[np.ndarray, np.ndarray]:
        import torch

        rows: list[np.ndarray] = []
        labels: list[float] = []
        for sequence in sequences:
            if sequence.scenario_id not in scenario_ids:
                continue
            rows.extend(
                vectorize_states([states_by_key[k].state for k in sequence.state_keys], schema)
            )
            labels.extend(sequence.infiltration.tolist())
        if not rows:
            return np.array([]), np.array([])
        batch = torch.as_tensor(np.stack(rows), dtype=torch.float32).unsqueeze(0)
        with torch.no_grad():
            _s, _r, risk_logits, _st = world.core.forward_sequence(batch)
        return torch.sigmoid(risk_logits).numpy().reshape(-1), np.asarray(labels)

    raw = {
        name: world_scores(ids)
        for name, ids in (
            ("train", train_ids),
            ("validation", manifest.validation_scenarios),
            ("test", manifest.test_scenarios),
        )
    }

    calibrator = None
    if world.result.risk_recalibration:
        calibrator = IsotonicCalibrator.from_payload(world.result.risk_recalibration)

    world_splits = []
    for name, (scores, labels) in raw.items():
        if not labels.size:
            continue
        entry = _summarise(name, scores, labels)
        if calibrator is not None:
            entry["after_recalibration"] = _summarise(name, calibrator.predict_many(scores), labels)
        world_splits.append(entry)

    payload["world_model"] = {
        "splits": world_splits,
        "threshold_sweep": _threshold_sweep(*raw["test"]) if raw["test"][0].size else [],
        "threshold_sweep_after_recalibration": (
            _threshold_sweep(raw["test"][0], calibrator.predict_many(raw["test"][0]))
            if calibrator is not None and raw["test"][0].size
            else []
        ),
        "recalibration_outcome": world.result.risk_recalibration_outcome,
        "recalibration_fitted": calibrator is not None,
    }
    return payload


def _fmt(value) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float):
        return f"{value:.3f}"
    return str(value)


def _render(payload: dict) -> str:
    lines = [
        "# Calibration report",
        "",
        f"- version: `{payload['report_version']}`",
        f"- dataset: `{payload['dataset_id']}` (**synthetic**, generated by this run)",
        f"- generated: {payload['generated_at']}",
        "",
        "Reliability, expected calibration error and the Brier decomposition. The",
        "decomposition is what separates *the probabilities are wrong* from *the",
        "predictions carry no information*: a model can be perfectly reliable and",
        "useless by always saying 0.5.",
        "",
    ]

    for section, title in (
        ("baseline", "Baseline risk head"),
        ("world_model", "World-model risk head"),
    ):
        block = payload.get(section, {})
        if not block.get("splits"):
            continue
        lines += [
            f"## {title}",
            "",
            "| split | n | base rate | mean p | bias | ECE | Brier | "
            "reliability | resolution | skill |",
            "|---|---|---|---|---|---|---|---|---|---|",
        ]
        for split in block["splits"]:
            lines.append(
                f"| {split['split']} | {split['n']} | {split['base_rate']:.3f} | "
                f"{split['mean_predicted']:.3f} | {split['bias']:+.3f} | {split['ece']:.4f} | "
                f"{split['brier']:.4f} | {split['reliability']:.4f} | "
                f"{split['resolution']:.4f} | {split['skill_vs_base_rate']:+.3f} |"
            )
        if block.get("threshold_sweep"):
            lines += [
                "",
                "| threshold | F1 | precision | recall | FPR |",
                "|---|---|---|---|---|",
            ]
            for row in block["threshold_sweep"]:
                lines.append(
                    f"| {row['threshold']:.2f} | {_fmt(row['f1'])} | "
                    f"{_fmt(row['precision'])} | {_fmt(row['recall'])} | "
                    f"{_fmt(row['false_positive_rate'])} |"
                )
        outcome = block.get("recalibration_outcome")
        if outcome:
            lines += [
                "",
                "### Isotonic recalibration (fitted on validation, reported on test)",
                "",
                f"- Brier: {outcome['brier_before']:.4f} -> {outcome['brier_after']:.4f} "
                f"({outcome['brier_improvement']:+.4f})",
                f"- ECE: {outcome['ece_before']:.4f} -> {outcome['ece_after']:.4f}",
                f"- bias: {outcome['bias_before']:+.4f} -> {outcome['bias_after']:+.4f}",
                f"- mean absolute shift: {outcome['mean_absolute_shift']:.4f}",
                f"- fit points: {outcome['n_fit']}",
                f"- ranking unchanged: {outcome['ranking_unchanged']}",
                "",
                "The curve is monotone, so it cannot change which window outranks",
                "which. It corrects the mapping from score to frequency and nothing",
                "else.",
            ]
        lines.append("")

    lines += ["## Warnings", ""]
    lines += [f"- {warning}" for warning in payload["warnings"]]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=23)
    parser.add_argument("--output", default="reports/generated/calibration")
    args = parser.parse_args()

    payload = run_report(seed=args.seed)
    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    (out / "calibration.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    (out / "calibration.md").write_text(_render(payload), encoding="utf-8")

    for section in ("baseline", "world_model"):
        for split in payload.get(section, {}).get("splits", []):
            print(
                f"{section:<12} {split['split']:<11} n={split['n']:<4} "
                f"bias={split['bias']:+.3f} ece={split['ece']:.4f} "
                f"brier={split['brier']:.4f} skill={split['skill_vs_base_rate']:+.3f}"
            )
    outcome = payload.get("world_model", {}).get("recalibration_outcome")
    if outcome:
        print(
            f"\nrecalibration: Brier {outcome['brier_before']:.4f} -> "
            f"{outcome['brier_after']:.4f}, ECE {outcome['ece_before']:.4f} -> "
            f"{outcome['ece_after']:.4f}, ranking_unchanged={outcome['ranking_unchanged']}"
        )
    for warning in payload["warnings"]:
        print(f"warning: {warning}")
    print(f"calibration_json={out / 'calibration.json'}")
    print(f"calibration_md={out / 'calibration.md'}")


if __name__ == "__main__":
    main()
