"""Try to walk past our own detectors, and report what it costs.

    uv run python scripts/run_evasion_report.py

Runs a red-team pass over real attacking windows: for each detector that fires,
it applies a closed set of physically executable evasions and measures whether
the rule actually stops alerting. Cost is reported in extra bytes on the wire and
extra windows of dwell time - not currency, because converting bytes to money
needs a deployment's own numbers.

The honest summary is the point. If nothing is evadable, that is the finding and
it gets said plainly. Synthetic data, generated by this run.
"""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path

from sentinel.detectors import run_all_detectors
from sentinel.evasion import EVASION_VERSION, red_team, render
from sentinel.synthetic import DATASET_ID, generate_labelled_states
from sentinel.targets import make_split_manifest

SCENARIOS = [f"ev{i:02d}" for i in range(10)]
HISTORY_WINDOWS = 6


def collect_windows(labelled, manifest, *, limit: int = 24) -> list:
    """Attacking windows with enough history for the new-edge rules to be live.

    Early windows are skipped deliberately: ``detect_lateral`` refuses to score
    above 0.5 until it has ``MIN_HISTORY`` windows, so red-teaming a cold start
    would report "not evadable" for a rule that was never armed.
    """
    windows = []
    for scenario in manifest.test_scenarios:
        states = sorted(
            [i for i in labelled if i.scenario_id == scenario],
            key=lambda i: i.state.window_start,
        )
        for index in range(HISTORY_WINDOWS, len(states) - 1):
            if not states[index].label.infiltration:
                continue
            history = tuple(s.state for s in states[max(0, index - HISTORY_WINDOWS) : index])
            windows.append((states[index].state, history))
            if len(windows) >= limit:
                return windows
    return windows


def run(seed: int = 53) -> dict:
    labelled = generate_labelled_states(SCENARIOS, seed=seed, window_seconds=60, stride_seconds=60)
    manifest = make_split_manifest(SCENARIOS, seed=seed)
    windows = collect_windows(labelled, manifest)
    report = red_team(windows, run_all_detectors)
    return {
        "version": EVASION_VERSION,
        "dataset_id": DATASET_ID,
        "generated_at": datetime.now(UTC).isoformat(),
        "report": report.as_dict(),
        "markdown": render(report),
        "warnings": [
            "All figures are from synthetic data generated by this run; they "
            "describe the generator, not any real network.",
            "Strategies are hand-enumerated from each rule's own definition. "
            "This prices the known evasions, not every evasion that exists.",
        ],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=53)
    parser.add_argument("--output", default="reports/generated/evasion")
    args = parser.parse_args()

    payload = run(seed=args.seed)
    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    (out / "evasion.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    (out / "evasion.md").write_text(payload["markdown"], encoding="utf-8")

    report = payload["report"]
    print(
        f"windows tested: {report['windows_tested']}  "
        f"detectors checked: {report['detectors_checked']}  "
        f"detectors that fired: {report['detectors_tested']}"
    )
    print(f"evadable detectors: {report['evadable_detectors'] or 'none'}")
    if report["free_evasions"]:
        print("FREE evasions found:")
        for move in report["free_evasions"]:
            print(f"  {move['detector']} via {move['name']}")
    else:
        print("no free evasions found")
    for move in report["moves"]:
        if move["evades"]:
            state = "feasible" if move["feasible"] else "NOT feasible (needs tampering)"
            print(
                f"  {move['detector']:<20} {move['name']:<34} {state} "
                f"cost={move['cost_bytes']:.0f}B/{move['cost_windows']:.1f}win"
            )
    for warning in payload["warnings"]:
        print(f"warning: {warning}")
    print(f"evasion_json={out / 'evasion.json'}")
    print(f"evasion_md={out / 'evasion.md'}")


if __name__ == "__main__":
    main()
