"""How much telemetry does this actually need, and what does it cost to collect?

    uv run python scripts/run_telemetry_budget.py

Refits the baseline on progressively smaller feature subsets and reports a
performance/cost frontier with a paired bootstrap interval on the loss from
dropping features. Writes a deployable ``telemetry_profile.yaml``.

The output deliberately does **not** say "N features are enough". It says the
smallest tested subset whose loss is inside the noise, and returns nothing at all
when no subset qualifies - which is the case a small validation split often
produces, and is the honest answer.

Synthetic data, generated by this run. Not a field benchmark.
"""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
from sklearn.linear_model import LogisticRegression

from sentinel.baseline import train_baseline
from sentinel.config import BaselineConfig
from sentinel.features import FeatureSchema, vectorize_states
from sentinel.synthetic import DATASET_ID, generate_labelled_states
from sentinel.targets import build_sequence_samples, make_split_manifest
from sentinel.telemetry_budget import (
    TELEMETRY_BUDGET_VERSION,
    ablation_curve,
    audit_tier_coverage,
    describe_profile,
    pareto_frontier,
)

SCENARIOS = [f"tb{i:02d}" for i in range(12)]
CANDIDATE_SIZES = (3, 5, 8, 12, 20)


def _train_brier(
    matrix: np.ndarray,
    labels: np.ndarray,
    train_mask: np.ndarray,
    columns: list[int],
    seed: int,
) -> float:
    """Mean squared error on the training split, used only to rank candidates."""
    model = LogisticRegression(max_iter=2000, random_state=seed)
    model.fit(matrix[train_mask][:, columns], labels[train_mask])
    probabilities = model.predict_proba(matrix[train_mask][:, columns])[:, 1]
    return float(np.mean((probabilities - labels[train_mask]) ** 2))


def forward_select(
    matrix: np.ndarray,
    labels: np.ndarray,
    train_mask: np.ndarray,
    names: list[str],
    sizes: tuple[int, ...],
    seed: int,
) -> dict[int, list[str]]:
    """Greedy forward selection, ranked on the **training** split only.

    Ranking by coefficient magnitude was tried first and is wrong: a feature with
    a small weight can be important *conditional on* the others, so the ordering
    is not a ranking of usefulness. It produced a jagged curve where 8 features
    looked indistinguishable from 98 while 12 looked measurably worse, which is
    incoherent for a nested family.

    Forward selection is at least monotone in the number of features, because
    each step is chosen to improve the objective. Selection sees only the
    training split; the validation split is held back for the bootstrap, so
    nothing here leaks into the reported comparison.
    """
    chosen: list[str] = []
    columns: list[int] = []
    result: dict[int, list[str]] = {}
    wanted = set(sizes)
    # One feature per step, up to the deepest candidate. The earlier version
    # added one feature per *candidate size*, so it walked 1,2,3...7 and never
    # reached 8, 12 or 20 - it was reporting the first seven sizes regardless of
    # what was asked for.
    for _step in range(max(wanted) if wanted else 0):
        remaining = [i for i in range(len(names)) if names[i] not in chosen]
        if not remaining:
            break
        best_name = None
        best_score = np.inf
        for index in remaining:
            trial = columns + [index]
            score = _train_brier(matrix, labels, train_mask, trial, seed)
            if score < best_score:
                best_score = score
                best_name = names[index]
        if best_name is None:
            break
        chosen.append(best_name)
        columns.append(names.index(best_name))
        if len(chosen) in wanted:
            result[len(chosen)] = list(chosen)
    return result


def _per_window_brier(
    matrix: np.ndarray,
    labels: np.ndarray,
    indices: dict,
    names: list[str],
    keep: list[str],
    seed: int,
) -> np.ndarray:
    """Per-window squared error on the validation split, refit on train only.

    Refitting rather than masking columns matters: a masked column is not the
    same as never collecting it, and masking flatters small subsets by leaving
    the remaining weights tuned to a full-information fit.

    The metric is the **Brier score**, not F1, and deliberately so. A bootstrap
    needs a per-window quantity, and F1 is not additive over windows - a bootstrap
    over F1 would need to resample and recompute a threshold-dependent count, and
    the resulting interval would be about the resampling rather than the loss.
    Brier is additive, proper, and threshold-free. Lower is better.
    """
    columns = [names.index(name) for name in keep]
    train_mask = indices["train"]
    validation_mask = indices["validation"]
    model = LogisticRegression(max_iter=2000, random_state=seed)
    model.fit(matrix[train_mask][:, columns], labels[train_mask])
    probabilities = model.predict_proba(matrix[validation_mask][:, columns])[:, 1]
    return (probabilities - labels[validation_mask]) ** 2


def run_budget(seed: int = 41) -> dict:
    labelled = generate_labelled_states(SCENARIOS, seed=seed, window_seconds=60, stride_seconds=60)
    manifest = make_split_manifest(SCENARIOS, seed=seed)
    samples = build_sequence_samples(labelled, sequence_length=2, horizon=1)
    reference = train_baseline(
        labelled, samples, manifest, config=BaselineConfig(decision_threshold=0.5), seed=seed
    )
    schema: FeatureSchema = reference.result.feature_schema
    names = list(schema.names)
    weights = np.asarray(reference.model.coef_).ravel().tolist()  # noqa: F841 - reported for context only

    states_by_key = {item.state_key: item for item in labelled}
    rows = [states_by_key[s.input_state_keys[-1]].state for s in samples]
    matrix = vectorize_states(rows, schema)
    labels = np.array([1.0 if s.target.target_infiltration else 0.0 for s in samples])
    index_of = {s.sample_id: i for i, s in enumerate(samples)}
    indices = {
        "train": np.array(
            [index_of[s.sample_id] for s in samples if s.scenario_id in manifest.train_scenarios]
        ),
        "validation": np.array(
            [
                index_of[s.sample_id]
                for s in samples
                if s.scenario_id in manifest.validation_scenarios
            ]
        ),
    }

    subsets = {"full": names}
    scores = {"full": _per_window_brier(matrix, labels, indices, names, names, seed)}
    selected = forward_select(matrix, labels, indices["train"], names, CANDIDATE_SIZES, seed)
    for size, keep in selected.items():
        subsets[f"top{size}"] = keep
        scores[f"top{size}"] = _per_window_brier(matrix, labels, indices, names, keep, seed)

    result = ablation_curve(subsets, scores, bootstrap_iterations=2000, seed=seed)

    # A sanity check on the cost model: how many features land in each tier, so a
    # prefix-list omission shows up as an implausible count rather than as a
    # quietly cheaper frontier.
    tier_counts = audit_tier_coverage(names)

    payload = {
        "version": TELEMETRY_BUDGET_VERSION,
        "dataset_id": DATASET_ID,
        "generated_at": datetime.now(UTC).isoformat(),
        "n_features": len(names),
        "tier_counts": tier_counts,
        "validation_windows": int(indices["validation"].size),
        "ablation": result.as_dict(),
        "frontier": [point.as_dict() for point in pareto_frontier(result.points)],
        "warnings": [
            "All figures are from synthetic data generated by this run; they "
            "describe the generator, not any real network.",
            "Feature subsets come from greedy forward selection scored on the "
            "training split. Ranking by coefficient magnitude was tried first "
            "and produced a non-monotone curve, because a small weight can still "
            "be important conditional on the others.",
            "Forward selection is greedy and can miss a subset that only works "
            "in combination. The bootstrap interval says 'no measurable loss on "
            "this validation split', not 'equally good'.",
        ],
    }
    return payload


def _render(payload: dict) -> str:
    ablation = payload["ablation"]
    lines = [
        "# Telemetry budget",
        "",
        f"- version: `{payload['version']}`",
        f"- dataset: `{payload['dataset_id']}` (**synthetic**, generated by this run)",
        f"- generated: {payload['generated_at']}",
        f"- features: **{payload['n_features']}**, validation windows: "
        f"**{payload['validation_windows']}**",
        "",
        "Collection tiers, which is the cost a deployment actually pays:",
        "",
        "| tier | features |",
        "|---|---|",
    ]
    for tier, count in payload["tier_counts"].items():
        lines.append(f"| {tier} | {count} |")
    lines += [
        "",
        "## Performance against collection cost",
        "",
        "| features | Brier (lower better) | cost | tiers | 95% CI on loss | indistinguishable? |",
        "|---|---|---|---|---|---|",
    ]
    for point in sorted(ablation["curve"], key=lambda p: p["n_features"]):
        ci = f"{point['ci_low']:+.4f} to {point['ci_high']:+.4f}"
        lines.append(
            f"| {point['n_features']} | {point['brier']:.4f} | {point['cost']:.2f} | "
            f"{', '.join(point['tiers'])} | {ci} | "
            f"{'yes' if point['indistinguishable_from_full'] else 'no'} |"
        )
    lines += ["", "## Recommendation", "", ablation["note"], ""]
    if ablation.get("recommendation"):
        profile = describe_profile(ablation["recommendation"])
        lines += [
            f"- features: {profile['n_features']} of {payload['n_features']}",
            f"- collection tiers required: {', '.join(profile['required_tiers'])}",
            f"- cost units: {profile['cost_units']:.2f}",
            "- written to `telemetry_profile.yaml` in this directory",
            "",
            "The features are:",
            "",
        ]
        lines += [f"  - `{name}`" for name in ablation["recommendation"]]
    lines += ["", "## Warnings", ""]
    lines += [f"- {warning}" for warning in payload["warnings"]]
    return "\n".join(lines) + "\n"


def _write_profile(payload: dict, out: Path) -> Path | None:
    recommendation = payload["ablation"].get("recommendation")
    if not recommendation:
        return None
    profile = describe_profile(recommendation)
    lines = [
        "# Generated by scripts/run_telemetry_budget.py - do not hand-edit.",
        "# The feature set below is the smallest tested subset whose loss from the",
        "# full model is inside the bootstrap noise. That is not a claim of",
        "# equivalence; re-run the script if the data changes.",
        "telemetry_profile_version: 1",
        f"dataset_id: {payload['dataset_id']}",
        f"n_features: {profile['n_features']}",
        f"cost_units: {profile['cost_units']:.3f}",
        "required_tiers:",
    ]
    lines += [f"  - {tier}" for tier in profile["required_tiers"]]
    lines += ["features:"]
    lines += [f"  - {name}" for name in profile["features"]]
    path = out / "telemetry_profile.yaml"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=41)
    parser.add_argument("--output", default="reports/generated/telemetry-budget")
    args = parser.parse_args()

    payload = run_budget(seed=args.seed)
    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    (out / "telemetry_budget.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    (out / "telemetry_budget.md").write_text(_render(payload), encoding="utf-8")
    profile_path = _write_profile(payload, out)

    ablation = payload["ablation"]
    print(f"features: {payload['n_features']}  validation windows: {payload['validation_windows']}")
    print(f"tiers: {payload['tier_counts']}")
    for point in sorted(ablation["curve"], key=lambda p: p["n_features"]):
        verdict = (
            "indistinguishable" if point["indistinguishable_from_full"] else "measurably worse"
        )
        print(
            f"  {point['n_features']:>3} features  brier={point['brier']:.4f}  "
            f"cost={point['cost']:.2f}  {verdict}"
        )
    print()
    print(ablation["note"])
    if profile_path:
        print(f"telemetry_profile={profile_path}")
    else:
        print("telemetry_profile=not written (no subset qualified)")
    for warning in payload["warnings"]:
        print(f"warning: {warning}")
    print(f"telemetry_budget_json={out / 'telemetry_budget.json'}")
    print(f"telemetry_budget_md={out / 'telemetry_budget.md'}")


if __name__ == "__main__":
    main()
