"""How many labelled scenarios does the model need, and does unlabelled data help?

    uv run python scripts/run_label_efficiency.py

Fits a masked-feature autoencoder on train-split windows without reading a label,
then spends a nested series of label budgets on both the raw features and the
learned representation, and reports each against its own full-data ceiling.

The output is built to be readable when the answer is "this cannot be measured
here". A label-efficiency curve on a saturated task is flat, and a flat curve is
indistinguishable from a curve on a hard task unless the ceiling is printed next
to it - so the ceiling and the headroom are in the table, not in a footnote.

Synthetic data, generated by this run. Not a statement about real label needs.
"""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path

import numpy as np

from sentinel.baseline import train_baseline
from sentinel.config import BaselineConfig
from sentinel.features import FeatureSchema, vectorize_states
from sentinel.label_efficiency import (
    LABEL_EFFICIENCY_VERSION,
    PRETRAINED,
    SCRATCH,
    encode,
    label_efficiency_curve,
    pretrain_encoder,
)
from sentinel.synthetic import DATASET_ID, generate_labelled_states
from sentinel.targets import build_sequence_samples, make_split_manifest

SCENARIOS = [f"le{i:02d}" for i in range(12)]
BUDGETS = (1, 2, 3, 4, 6)


def run(seed: int = 51) -> dict:
    labelled = generate_labelled_states(SCENARIOS, seed=seed, window_seconds=60, stride_seconds=60)
    manifest = make_split_manifest(SCENARIOS, seed=seed)
    samples = build_sequence_samples(labelled, sequence_length=2, horizon=1)
    reference = train_baseline(
        labelled, samples, manifest, config=BaselineConfig(decision_threshold=0.5), seed=seed
    )
    schema: FeatureSchema = reference.result.feature_schema

    states_by_key = {item.state_key: item for item in labelled}
    rows = [states_by_key[s.input_state_keys[-1]].state for s in samples]
    raw = vectorize_states(rows, schema)
    labels = np.array([1.0 if s.target.target_infiltration else 0.0 for s in samples])

    index_of = {s.sample_id: i for i, s in enumerate(samples)}
    train_rows = np.array(
        [index_of[s.sample_id] for s in samples if s.scenario_id in manifest.train_scenarios]
    )
    evaluation_rows = np.array(
        [index_of[s.sample_id] for s in samples if s.scenario_id in manifest.validation_scenarios]
    )
    scenario_of_row = np.array([s.scenario_id for s in samples])

    # The unlabelled pool is every train-split window, including the ones the
    # label budgets will later be spent on. Their labels are simply never read,
    # which is what makes the encoder self-supervised rather than merely small.
    encoder, pretraining = pretrain_encoder(raw[train_rows], seed=seed)
    representations = {SCRATCH: raw, PRETRAINED: encode(encoder, raw)}

    result = label_efficiency_curve(
        representations,
        labels,
        train_rows,
        evaluation_rows,
        scenario_of_row,
        BUDGETS,
        seed=seed,
    )
    result.pretraining = pretraining

    payload = {
        "version": LABEL_EFFICIENCY_VERSION,
        "dataset_id": DATASET_ID,
        "generated_at": datetime.now(UTC).isoformat(),
        "train_windows": int(train_rows.size),
        "evaluation_windows": int(evaluation_rows.size),
        "evaluation_split": "validation",
        "budgets_scenarios": list(BUDGETS),
        "result": result.as_dict(),
        "warnings": [
            "All figures are from synthetic data generated by this run; they "
            "describe the generator, not any real network.",
            "scratch sees all 98 raw features and pretrained sees the encoder's "
            "narrower output, so the two rows differ in width as well as in "
            "training. That is what a representation is, and the width is printed "
            "rather than averaged away.",
            "Budgets are nested prefixes of one seeded shuffle, so each point is a "
            "strict subset of the next and the curve cannot rise by luck.",
            "The bootstrap interval compares each budget against the same method's "
            "own full-data ceiling, not against the other method.",
        ],
    }
    return payload


def _render(payload: dict) -> str:
    result = payload["result"]
    pretraining = result["pretraining"]
    lines = [
        "# Label efficiency",
        "",
        f"- version: `{payload['version']}`",
        f"- dataset: `{payload['dataset_id']}` (**synthetic**, generated by this run)",
        f"- generated: {payload['generated_at']}",
        f"- train windows: **{payload['train_windows']}**, "
        f"{payload['evaluation_split']} windows: **{payload['evaluation_windows']}**",
        "",
        "## Self-supervised step",
        "",
        f"- fitted on **{pretraining['n_unlabelled_windows']}** unlabelled windows, "
        f"labels used: **{pretraining['labels_used']}**",
        f"- masked **{pretraining['mask_fraction']:.0%}** of features, "
        f"{pretraining['epochs']} epochs, latent width {pretraining['latent']}",
        f"- reconstruction loss: {pretraining['reconstruction_loss'][0]:.4f} -> "
        f"{pretraining['reconstruction_loss'][-1]:.4f}",
        "",
        pretraining["note"],
        "",
        "## Ceiling and headroom",
        "",
        "A flat curve means nothing without the number it is flat against.",
        "",
        "| method | Brier trained on everything | Brier from one scenario | headroom |",
        "|---|---|---|---|",
    ]
    for method in (SCRATCH, PRETRAINED):
        lines.append(
            f"| {method} | {result['references'][method]:.4f} | "
            f"{result['first_budget_brier'][method]:.4f} | "
            f"{result['headroom'][method]:+.4f} |"
        )
    lines += [
        "",
        "## Curve",
        "",
        "| method | scenarios | samples | features | Brier | loss | 95% CI | at ceiling? |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for point in sorted(result["curve"], key=lambda p: (p["method"], p["n_scenarios"])):
        ci = f"{point['ci_low']:+.4f} to {point['ci_high']:+.4f}"
        lines.append(
            f"| {point['method']} | {point['n_scenarios']} | {point['n_samples']} | "
            f"{point['n_features']} | {point['brier']:.4f} | "
            f"{point['loss_from_full']:+.4f} | {ci} | "
            f"{'yes' if point['indistinguishable_from_full'] else 'no'} |"
        )
    lines += ["", "## Reading", "", result["note"], "", "## Warnings", ""]
    lines += [f"- {w}" for w in payload["warnings"]]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=51)
    parser.add_argument("--output", default="reports/generated/label-efficiency")
    args = parser.parse_args()

    payload = run(seed=args.seed)
    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    (out / "label_efficiency.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    (out / "label_efficiency.md").write_text(_render(payload), encoding="utf-8")

    result = payload["result"]
    pretraining = result["pretraining"]
    print(
        f"pretrain: {pretraining['reconstruction_loss'][0]:.4f} -> "
        f"{pretraining['reconstruction_loss'][-1]:.4f} reconstruction loss, "
        f"{pretraining['labels_used']} labels used"
    )
    for method in (SCRATCH, PRETRAINED):
        print(
            f"{method:>10}: ceiling {result['references'][method]:.4f}  "
            f"headroom {result['headroom'][method]:+.4f}"
        )
        for point in sorted(result["curve"], key=lambda p: p["n_scenarios"]):
            if point["method"] != method:
                continue
            verdict = "at ceiling" if point["indistinguishable_from_full"] else "below"
            print(f"  {point['n_scenarios']:>2} scenarios  brier={point['brier']:.4f}  {verdict}")
    print()
    print(result["note"])
    for warning in payload["warnings"]:
        print(f"warning: {warning}")
    print(f"label_efficiency_json={out / 'label_efficiency.json'}")
    print(f"label_efficiency_md={out / 'label_efficiency.md'}")


if __name__ == "__main__":
    main()
